export const USER_STATUS = {
  OFFLINE: 0,
  ONLINE: 1,
}

export const HTTP_STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
}

export const RESPONSE_CODE = {
  OK: 20000,
  CREATED: 20001,
  UNAUTHORIZED: 30001,
  USER_ALREADY_EXIST: 30002,
  INVALID_INPUT: 30003,
  INTERNAL_SERVER_ERROR: 31000,
}

export const RESPONSE_MESSAGE = {
  SUCCESS: 'Success',
  LOGGED_IN: 'Logged in successfully',
  UNAUTHORIZED: 'Unauthorized',
  USER_ALREADY_EXIST: 'User is already exists',
  NOT_FOUND: 'Not found',
}
